#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nmbondtest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#datasource
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #mapper映射文件路径
  type-aliases-package: org.itheima.springboot.firstspringboot.domain
  #check-config-location: 指定mybatis的核心配置文件